### ISSUE TITLE
Topological sorting loop error

### ISSUE THREAD

**Issue by dsvalenciah** [coreofscience/python-sap#16]
* Python ToS version:
* Python version:
* Operating System:

### Description
![image](https://user-images.githubusercontent.com/19624616/81096143-98209980-8ecb-11ea-9602-f6475a112664.png)

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by odarbelaeze** [comment]
We good on this front as of https://github.com/coreofscience/python-sap/releases/tag/v1.0.0
