### ISSUE TITLE
unlinked dois with webpages

### ISSUE THREAD

**Issue by srobledog** [coreofscience/python-sap#18]
* Python ToS version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

![image](https://user-images.githubusercontent.com/8762305/82732845-7f8aee80-9cd5-11ea-991f-6dee5ed77572.png)

Sometimes, dois are not linked with webpages in sap results from terminal 

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by odarbelaeze** [comment]
I'm not sure if you mean you can't click through the link. Terminals don't have universal support for links, I mean, we're not making anything special to make those links clickable, the terminal software might see that the text is indeed a link and allowing to click through.

**Comment by odarbelaeze** [comment]
I'm closing this one because it's not a problem with the tool itself.

If you want to have a better looking view of the results, you can use the Jupyter based tool available here: https://mybinder.org/v2/gh/coreofscience/python-sap/main?urlpath=lab/tree/example/example.ipynb
